service: orders-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: orders-table
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.DYNAMODB_TABLE}

functions:
  createOrder:
    handler: src/handlers/createOrder.handler
    events:
      - http:
          path: orders
          method: post

  getOrder:
    handler: src/handlers/getOrder.handler
    events:
      - http:
          path: orders/{orderId}
          method: get

  updateOrder:
    handler: src/handlers/updateOrder.handler
    events:
      - http:
          path: orders/{orderId}
          method: put

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
